### JSON Logger configuration ###

json:
  logger:
    disabledFields: "content" #Indicate which fields to be completely removed
    contentDataMasking : "" #Indiate which fields to be masked as hidden

api:
  key: "1" # replace with read API Id once added to API manager

https:
  keystore:
    path: "keystores/localhost.p12"
    password: "![pSgr3hKKWtqWpPRMA25kfw==]"
 
cache:    
  entry:
    ttl: "86400"
    maxEntries: "10"
  default:
      value: "NOT_CACHED"

# hashing details to encrypt cached data
hash:
  key: "![wLB3YBcE/Jg430nxrs0S8JXhCAWTqqB+CxYoB437ByWRoDwFh6WIWXHP5ffHtFNAPR1NwnVL51tJgrCOsuYhH4a3QPsZg+jV]"
  
sps:
  api:
    protocol: "HTTPS"
    method: "GET"
    host: "api.spscommerce.com"
    basepath: "/transactions/v5/data"
    path : "/testout/"
    response.timeout: "10000"
    connection.idle.timeout: "30000"
  auth:
    protocol: "HTTPS"
    method: "POST"
    host: "auth.spscommerce.com"
    path: "/oauth/token"
    response.timeout: "10000"
    connection.idle.timeout: "30000"
   