name: 'XML Lint'
description: 'Lint XML files with xmllint'
inputs:
  xml-file:
    description: 'The source (.xml) file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.xml-file }}
    - schematron
    - ./codeReview/mule-flow.sch
