name: Code review

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.5
        with:
          separator: ","
          files: |
            ^sumup(-\w+)+-sapi\/
      
      - name: Get project name
        id: project-name
        run: |
          project_name=$(echo "${{ steps.changed-files.outputs.all_modified_files }}" | cut -d '/' -f 1 | xargs)
          echo "::set-output name=projectName::$project_name"
          
      - name: Get files to do code review
        id: code-review-files
        run: |
          variable='${{ steps.changed-files.outputs.all_modified_files }}'
          for i in ${variable//,/ }
          do
          if [[ $i == *'/globals/config.xml'* ]]
          then echo "::set-output name=globalsConfigMuleFiles::$i"
          else echo "::set-output name=muleFiles::$i"
          fi
          done
                  
      - name: Code review of Global Config Mule XML
        #if: contains(steps.changed-files.outputs.all_modified_files, '/globals/config.xml')
        uses: ./codeReview/
        id: reviewGloablConfigXML
        with : 
          xml-file : ${{ steps.code-review-files.outputs.globalsConfigMuleFiles }}
          xml-schema-file : ./codeReview/mule-globals-config.sch
     
      - name: Code review of Other Mule XML
        #if: contains(steps.changed-files.outputs.all_modified_files, '/globals/config.xml')
        uses: ./codeReview/
        id: reviewMuleXML
        with : 
          xml-file : ${{ steps.code-review-files.outputs.muleFiles }}
          xml-schema-file : ./codeReview/mule-flow.sch
