name: Code review

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get files to do code review
        id: code-review-files
        run: |
          variable='sumup-purchase-orders-sps-sapi/src/main/mule/globals/config.xml,sumup-purchase-orders-sps-sapi/src/main/mule/globals/globalErrorHandler.xml'
          for i in ${variable//,/ }
          do
          if [[ $i == *'/globals/config.xml'* ]]
          then echo "::set-output name=globalsConfig::$i"
          fi
          done
                  
      - name: Code review of Global Config Mule XML
        if: contains(steps.changed-files.outputs.all_modified_files, '/globals/config.xml')
        uses: ./codeReview/
        id: reviewGloablConfigXML
        with : 
          xml-file : ${{ steps.code-review-files.outputs.globalsConfig }}
          xml-schema-file : ./codeReview/mule-globals-config.sch
