name: Code review

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Code reiew
        uses: ./codeReview/ # Uses an action in the root directory
        id: review
        with : 
          xml-file : ./sumup-purchase-orders-sps-sapi/src/main/mule/sumup-purchase-orders-sps-sapi.xml
